# Generated by Django 4.1.7 on 2023-02-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_user',
        ),
    ]
